version: '3'

networks:
  vscs:
    external: false
    
services:
  vscs:
    image: codercom/code-server:latest
    container_name: vscs
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - PASSWORD=dg170MH361802
    restart: always
    privileged: true
    networks:
      - vscs
    volumes:
      # - ./.config:/home/coder/.config
      - ./project:/home/coder/project
    ports:
      - "9780:8080"